### ISSUE TITLE
Rename `support/2.x` branch to `v2`?

### ISSUE THREAD

**Issue by dstansby** [zarr-developers/zarr-python#2345]
I'd like to advocate for the v2 branch, currently called `support/2.x` to be renamed to `v2`, because:

- It mirrors `v3`, which we've been using for a while
- It's many less characters to type when switching branches

Thoughts?

**Comment by d-v-b** [comment]
Simply mirroring v3 doesn't seem useful, because to me `v3` and `support/v2` are not analogous. `v3` is an _active_ branch off of `main`, that will eventually become `main`. Whereas `support/v2` will be an _inactive_ branch off of `main`, that will never be merged back into `main`. For me this kind of answers the second concern too -- because `support/v2` will not be under extensive development, the cost of the extra characters is, IMO, low. 

An advantage to `support/v2` (or `legacy/v2`, or any other prefix) is that when we start working on `zarr-python` 4,.x we can make `support/v3` :)

**Comment by dstansby** [comment]
Can we at least go with `support/v2` instead of `support/2.x` (the current name) then?

When we start working on v4, we could make a `v3` branch...

**Comment by d-v-b** [comment]
ah, I didn't even notice that I was talking about `support/v2` but the current name is `support/2.x`. Sorry for the confusion. I personally don't have a strong preference between them. How do you feel about `support/v2` @jhamman ?

**Comment by jhamman** [comment]
Look, this is not something I'm willing to squabble over! I'm fine with `support/v2`. The `support/2.x` is following a pattern I've seen elsewhere (a la gitflow) but it really doesn't matter to me. 

@dstansby - if you want to push a new branch called `support/v2`, I'm fine with it. Just do it soon because we're in a holding pattern on `main` until #2341 goes in.

I also switched a few PRs (tagged with [`v2`](https://github.com/zarr-developers/zarr-python/pulls?q=is%3Apr+is%3Aopen+label%3AV2)) to use the `support/2.x` branch as their base. So we should correct those before deleting the existing support branch.

**Comment by dstansby** [comment]
👍 I renamed `support/2.x` to `support/v2`, which seems like a good halfway between `v2` and `support/2.x` that we can agree on :)
