### ISSUE TITLE
Make consolidated metadata fetch opt-in

### ISSUE THREAD

**Issue by dcherian** [zarr-developers/zarr-python#2528]
### Zarr version

main

### Numcodecs version

...

### Python Version

...

### Operating System

...

### Installation

...

### Description

Icechunk for example, does not implement this and these requests are wasted gets/sets. Stores should opt-in to this behaviour

### Steps to reproduce

...

**Comment by TomAugspurger** [comment]
> Stores should opt-in to this behaviour

Probably opt-out, right? The current behavior, of `use_consolidated=None`, matches the behavior from V2, which is to use it if present. With something like `Store.supports_consolidated_metadata`, we could set `use_consolidated=store.supports_consolidated_metadata` and skip it when we know it's not present.


And just a note: I think this only affects Zarr v2, since in Zarr v3 the consolidated metadata is in the same `zarr.json` as the other metadata.

**Comment by dcherian** [comment]
Yes, now I think that the issue that motivated this comment is on the Xarray side: https://github.com/pydata/xarray/pull/9848

**Comment by dstansby** [comment]
> And just a note: I think this only affects Zarr v2, since in Zarr v3

Just to confirm, this is an issue with creating zarr v2 data in zarr-python v3?

**Comment by TomAugspurger** [comment]
>> And just a note: I think this only affects Zarr v2, since in Zarr v3
> Just to confirm, this is an issue with creating zarr v2 data in zarr-python v3?

"This" here was referring to the spurious / extra read of the consolidated metadata for Zarr V2 data. IMO, there's nothing left to do in this issue now that https://github.com/pydata/xarray/pull/9848 is fixed. zarr-python v3 doesn't make any extra requests for Zarr v3 data, and I believe it matches the behavior of zarr-python 2.x for Zarr v2 data.
