### ISSUE TITLE
opening zarr ZipStore requires write access even with mode="r"

### ISSUE THREAD

**Issue by hardingnj** [zarr-developers/zarr-python#269]
```bash
-rw-r--r-- 1 root user 18M Jun 29 10:11 testzarr.zip
```

```python
z = zarr.open_group("testzarr.zip", mode="r")
```
Returns a permissions error. 

#### Version and installation information
Please provide the following:

* Value of ``zarr.__version__`` 2.2.0
* Value of ``numcodecs.__version__`` 0.15
* Version of Python interpreter: 3.6.5
* Linux njh-OptiPlex-9020 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* via conda

**Comment by hardingnj** [comment]
Workaround (thanks @alimanfoo)

```python
store = zarr.ZipStore('testzarr.zip', mode='r')
z = zarr.Group(store)
```

**Comment by alimanfoo** [comment]
Thanks @hardingnj. 

For reference the problem is that the mode argument is not getting passed down to the code that turns the file path into a store. I.e., at [this line](https://github.com/zarr-developers/zarr/blob/master/zarr/hierarchy.py#L1104) where ``_normalize_store_arg()`` is called. The [normalize_store_arg()](https://github.com/zarr-developers/zarr/blob/master/zarr/creation.py#L128) function should accept some argument to tell it store should be read only.

**Comment by jakirkham** [comment]
The first link appears to have gone stale. Do you have a permalink, @alimanfoo?

**Comment by alimanfoo** [comment]
I've updated the [comment above](https://github.com/zarr-developers/zarr/issues/269#issuecomment-401359223) with permalinks.

**Comment by jakirkham** [comment]
Is `normalize_store_arg` intended to be part of the public API? If not, maybe we can just change `clobber` to `mode`.
