### ISSUE TITLE
Special treatment of NaN in JSON user attributes

### ISSUE THREAD

**Issue by meggart** [zarr-developers/zarr-python#412]
This is a problem that showed up when testing the Zarr Julia interface. Currently nan-values in user-attribute values are not converted to strings (see example below), which does not adhere to JSON specs and causes the Julia JSON parser to fail. So I would suggest to do something analogous to the `fill_value` entry in `.zarray`, i.e. to either forbid `nan` in zarr user attributes or convert them to strings to make the resulting JSON valid.

```python
import zarr
import numpy
z1 = zarr.open('attrtest')
z1.attrs['att1']=numpy.nan

with open('attrtest/.zattrs') as myfile:
    print(myfile.read())
```

**Comment by manzt** [comment]
Just want to keep track of this: https://github.com/zarr-developers/community/issues/37#issuecomment-726339050

`NaN` as `fill_value` seem to be converted to strings, but more care needs to be taken when parsing `.zattrs` in other languages since python will not but `NaN` into strings by default, and `NaN` is not valid JSON.

**Comment by Carreau** [comment]
This is also related to https://github.com/zarr-developers/zarr-specs/issues/81, the stdlib json does not respect the json spec, and we should decide what to do about this.

**Comment by jhamman** [comment]
This was included in the v3 spec: https://zarr-specs.readthedocs.io/en/latest/v3/core/v3.0.html#fill-value
