### ISSUE TITLE
attrs as kwarg 

### ISSUE THREAD

**Issue by d-v-b** [zarr-developers/zarr-python#538]
Is there any reason why it's not possible to set the attrs of an array / group by passing a kwarg to the  relevant creation function? e.g.: 
```python
z = zarr.create((10,10),chunks=(1,1), attrs={'foo':10})
```
(The current behavior is to ignore the `attrs` kwarg)
Looking back in time, I see this discussion: #121. It seems attrs as a kwarg was not pursued because of concerns about matching the behavior of hdf5? How relevant is that concern today>

**Comment by alimanfoo** [comment]
Hi @d-v-b, sorry you didn't get a reply to this at the time. 

#121 got closed because the original complaint was that '.zattrs' got written twice when you create an array then set attributes. We resolved that by modifying the library so that '.zattrs' was created lazily the first time the user tried to write some attributes.

However I can see that it would be convenient to also support `attrs` in the array creation functions, so no objection from me to adding support for that.

**Comment by jhamman** [comment]
this is done as part of the 3.0 release. Coming soon :).
