### ISSUE TITLE
Dtype shape deprecation

### ISSUE THREAD

**Issue by Carreau** [zarr-developers/zarr-python#591]
from  https://github.com/numpy/numpy/issues/17173

It looks like in master of numpy dtype of the form `(shape)type` might stop working in some places, if it's likely going to go through a deprecation cycle we should make sure zarr can handle that.

Currently the test suite would fail.

**Comment by jakirkham** [comment]
Do you know where we are using this?

**Comment by Carreau** [comment]
It is used in a few tests. 

In encode/decode dtype I think this might get serialized/deserialized, so there might be zarr files in the wild with that.

**Comment by Carreau** [comment]
https://github.com/zarr-developers/zarr-python/blob/5bf61efc533c880d6b991eb2eec1cf147e6d5e61/zarr/tests/test_core.py#L978

https://github.com/zarr-developers/zarr-python/blob/5bf61efc533c880d6b991eb2eec1cf147e6d5e61/zarr/tests/test_core.py#L1053

Are two examples.

**Comment by seberg** [comment]
@Carreau the second example should be fine though? It is a subarray embedded into a structured dtyped.  The only problem is a "bare" subarray dtype, because in that case NumPy actually returns an `"f4"` array, and not a `"(2,2)f4"` array.

I have to see, I might just resurrect the old code path for this one case (I don't like that but...).  Let me know if you know of any actual use case/users of this syntax.

**Comment by jhamman** [comment]
I couldn't find any evidence of this pattern in the v3 test suite so closing as stale.
