### ISSUE TITLE
Include fsspec in conda-forge testing?

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/zarr-python#820]
See:
 * https://github.com/conda-forge/zarr-feedstock/pull/48
 * #819 

The 2.9.0 tag of zarr-python failed to build on conda-forge since [fsspec tests weren't skipped everywhere](https://github.com/zarr-developers/zarr-python/issues/817) and conda-forge installs only a minimal environment.

Either we should test the same environment in this repo or update the conda-forge metadata to install more requirements.

**Comment by jrbourbeau** [comment]
FWIW over in Dask we have a few minimum dependencies builds which have been useful to ensure that things run with our specified minimum set of dependencies (both in terms of the set of packages installed as well as the minimum supported versions). This CI build has caught a number of subtle breakages that would have otherwise mostly likely gone unnoticed
